### ISSUE TITLE
Unable to find a specification for `ZXingObjC (~> 3.0)`

### ISSUE THREAD

**Issue by cutout33** [NathanaelA/nativescript-zxing#2]
Hi,

Am trying to use your plugin but after adding it to my project iOS fails to run with the following error

```
[!] Unable to find a specification for `ZXingObjC (~> 3.0)`
Processing node_modules failed. Error: Command sandbox-pod failed with exit code 1
```

on android I get the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Class com.google.zxing.pdf417.PDF417ResultMetadata conflict: /Users/fadi/Documents/appseleon/projects/bcard/bcard/platforms/android/build/intermediates/exploded-aar/barcodescanner-release-2.0.2/jars/classes.jar and /Users/fadi/.gradle/caches/modules-2/files-2.1/com.google.zxing/core/3.2.1/2287494d4f5f9f3a9a2bb6980e3f32053721b315/core-3.2.1.jar
    at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
    at com.telerik.metadata.Builder.build(Builder.java:39)
    at com.telerik.metadata.Generator.main(Generator.java:44)
```

**Comment by cutout33** [comment]
Was able to fix with the following:

```
pod repo remove master
pod setup
```

Thanks!
